export const GET_PLAYLIST = 'GET_PLAYLIST';
export const SET_PLAYLIST = 'SET_PLAYLIST';
export const GET_CURRENT_TRACK = 'GET_CURRENT_TRACK';
export const SET_CURRENT_TRACK = 'SET_CURRENT_TRACK';
export const GET_PLAYER_STATE = 'GET_PLAYER_STATE';
export const SET_PLAYER_STATE = 'SET_PLAYER_STATE';
export const TOGGLE_PLAY_STATE = 'TOGGLE_PLAY_STATE';