export const SET_TOKEN = 'SET_TOKEN';

export const GET_PLAYLIST = 'GET_PLAYLIST';
export const SET_PLAYLIST = 'SET_PLAYLIST';

export const GET_CURRENT_TRACK = 'GET_CURRENT_TRACK';
export const SET_CURRENT_TRACK = 'SET_CURRENT_TRACK';

export const SET_NEXT_TRACK = 'SET_NEXT_TRACK';
export const SET_PREVIOUS_TRACK = 'SET_PREVIOUS_TRACK';

export const GET_PLAYER_STATE = 'GET_PLAYER_STATE';
export const SET_PLAYER_STATE = 'SET_PLAYER_STATE';

export const TOGGLE_PLAY_STATE = 'TOGGLE_PLAY_STATE';

export const SET_ELAPSED_TIME = 'SET_ELAPSED_TIME';